// Generated by gencpp from file nmea_navsat_driver/bds.msg
// DO NOT EDIT!


#ifndef NMEA_NAVSAT_DRIVER_MESSAGE_BDS_H
#define NMEA_NAVSAT_DRIVER_MESSAGE_BDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nmea_navsat_driver
{
template <class ContainerAllocator>
struct bds_
{
  typedef bds_<ContainerAllocator> Type;

  bds_()
    : header()
    , status(0)
    , num(0)  {
    }
  bds_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(0)
    , num(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _status_type;
  _status_type status;

   typedef int8_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::nmea_navsat_driver::bds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nmea_navsat_driver::bds_<ContainerAllocator> const> ConstPtr;

}; // struct bds_

typedef ::nmea_navsat_driver::bds_<std::allocator<void> > bds;

typedef boost::shared_ptr< ::nmea_navsat_driver::bds > bdsPtr;
typedef boost::shared_ptr< ::nmea_navsat_driver::bds const> bdsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nmea_navsat_driver::bds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nmea_navsat_driver::bds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nmea_navsat_driver::bds_<ContainerAllocator1> & lhs, const ::nmea_navsat_driver::bds_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nmea_navsat_driver::bds_<ContainerAllocator1> & lhs, const ::nmea_navsat_driver::bds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nmea_navsat_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nmea_navsat_driver::bds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nmea_navsat_driver::bds_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmea_navsat_driver::bds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmea_navsat_driver::bds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmea_navsat_driver::bds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmea_navsat_driver::bds_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nmea_navsat_driver::bds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b7a97cf9f966fa10326f126f2a14d27";
  }

  static const char* value(const ::nmea_navsat_driver::bds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b7a97cf9f966fa1ULL;
  static const uint64_t static_value2 = 0x0326f126f2a14d27ULL;
};

template<class ContainerAllocator>
struct DataType< ::nmea_navsat_driver::bds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nmea_navsat_driver/bds";
  }

  static const char* value(const ::nmea_navsat_driver::bds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nmea_navsat_driver::bds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 status\n"
"int8 num\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nmea_navsat_driver::bds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nmea_navsat_driver::bds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nmea_navsat_driver::bds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nmea_navsat_driver::bds_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NMEA_NAVSAT_DRIVER_MESSAGE_BDS_H
