// Generated by gencpp from file nmea_navsat_driver/speed.msg
// DO NOT EDIT!


#ifndef NMEA_NAVSAT_DRIVER_MESSAGE_SPEED_H
#define NMEA_NAVSAT_DRIVER_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nmea_navsat_driver
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : header()
    , speed(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::nmea_navsat_driver::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nmea_navsat_driver::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::nmea_navsat_driver::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::nmea_navsat_driver::speed > speedPtr;
typedef boost::shared_ptr< ::nmea_navsat_driver::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nmea_navsat_driver::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nmea_navsat_driver::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nmea_navsat_driver::speed_<ContainerAllocator1> & lhs, const ::nmea_navsat_driver::speed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nmea_navsat_driver::speed_<ContainerAllocator1> & lhs, const ::nmea_navsat_driver::speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nmea_navsat_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nmea_navsat_driver::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nmea_navsat_driver::speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmea_navsat_driver::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nmea_navsat_driver::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmea_navsat_driver::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nmea_navsat_driver::speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nmea_navsat_driver::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d97c628937d47552ba5fcce4399ed962";
  }

  static const char* value(const ::nmea_navsat_driver::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd97c628937d47552ULL;
  static const uint64_t static_value2 = 0xba5fcce4399ed962ULL;
};

template<class ContainerAllocator>
struct DataType< ::nmea_navsat_driver::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nmea_navsat_driver/speed";
  }

  static const char* value(const ::nmea_navsat_driver::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nmea_navsat_driver::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::nmea_navsat_driver::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nmea_navsat_driver::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nmea_navsat_driver::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nmea_navsat_driver::speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NMEA_NAVSAT_DRIVER_MESSAGE_SPEED_H
